name: green_grow
description: Приложение для выращивания микрозелени дома — каталог, лотки и советы по уходу.
publish_to: "none"
version: 1.0.3+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/radish.png
